spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:55432/product_db"
    username: postgres
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update